### ISSUE TITLE
Add current build to repo

### ISSUE THREAD

**Issue by kruligh** [EOSArgentina/assemblyscript#1]
Hi, I used to have some troubles. I want to use this in that way:

`npm install EOSArgentina/assemblyscript' 

But in dist in repo is old, it,s bundled old code, so, for now, I have to clone repo, build, link. 

I think that build project and commit new dist is good idea.

**Comment by MaxGraey** [comment]
What about just download (install) AssemblyScript from [original repo](https://github.com/AssemblyScript/assemblyscript)?
